
[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
opacity = 1



[selection]
save_to_clipboard = true

[font]
normal = { family = 'JetBrains Mono SemiBold', style = 'Regular'}

[general]
live_config_reload = true
 
import = [
  "~/.config/alacritty/catppuccin-macchiato.toml"
]
